-- Enriched food data
INSERT INTO foods (id, name_tr, name_en, cuisine, moods, regions, is_vegetarian, is_vegan, is_gluten_free, description_tr, description_en) VALUES
('pho', 'Pho', 'Pho', 'vietnamese', '["relaxed","happy"]', '[]', 0, 0, 1, 'Geleneksel Vietnam pirinç eriştesi çorbası.', 'Traditional Vietnamese rice noodle soup.'),
('bibimbap', 'Bibimbap', 'Bibimbap', 'korean', '["energetic","happy"]', '[]', 0, 0, 0, 'Kore usulü karışık sebzeli pirinç tabağı.', 'Korean mixed rice bowl with vegetables.'),
('pad_thai', 'Pad Thai', 'Pad Thai', 'thai', '["happy","energetic"]', '[]', 0, 0, 1, 'Tayland usulü kızarmış pirinç eriştesi.', 'Thai stir-fried rice noodles.'),
('dim_sum', 'Dim Sum', 'Dim Sum', 'chinese', '["happy","relaxed"]', '[]', 0, 0, 0, 'Çeşitli küçük Çin lezzetleri.', 'A variety of small Chinese bite-sized dishes.'),
('ceviche', 'Ceviche', 'Ceviche', 'peruvian', '["energetic","relaxed"]', '[]', 0, 0, 1, 'Narenciye ile marine edilmiş taze balık.', 'Fresh raw fish cured in citrus juices.'),
('moussaka', 'Musakka', 'Moussaka', 'greek', '["happy","tired"]', '[]', 0, 0, 0, 'Patlıcanlı ve kıymalı geleneksel fırın yemeği.', 'Traditional eggplant and minced meat bake.'),
('paella', 'Paella', 'Paella', 'spanish', '["happy","energetic"]', '[]', 0, 0, 1, 'İspanyol usulü deniz ürünlü pirinç yemeği.', 'Spanish seafood rice dish.'),
('schnitzel', 'Şinitzel', 'Schnitzel', 'austrian', '["happy","tired"]', '[]', 0, 0, 0, 'Avusturya usulü pane edilmiş et.', 'Austrian-style breaded and fried meat.'),
('poutine', 'Poutine', 'Poutine', 'canadian', '["happy","sad"]', '[]', 1, 0, 0, 'Gravy soslu ve peynirli patates kızartması.', 'French fries topped with cheese curds and gravy.'),
('ratatouille', 'Ratatouille', 'Ratatouille', 'french', '["relaxed","happy"]', '[]', 1, 1, 1, 'Fransız usulü fırınlanmış bahçe sebzeleri.', 'French-style baked vegetable stew.'),
('tiramisu', 'Tiramisu', 'Tiramisu', 'italian', '["happy","sad"]', '[]', 1, 0, 0, 'Kahveli ve mascarpone peynirli İtalyan tatlısı.', 'Coffee-flavored Italian dessert with mascarpone.'),
('gelato', 'Gelato', 'Gelato', 'italian', '["happy","relaxed"]', '[]', 1, 0, 1, 'Yoğun kıvamlı İtalyan dondurması.', 'Rich and dense Italian ice cream.'),
('falafel_wrap', 'Falafel Dürüm', 'Falafel Wrap', 'middle_eastern', '["energetic","happy"]', '[]', 1, 1, 0, 'Lavaş arası çıtır falafel ve tahin sos.', 'Crispy falafel and tahini sauce in a wrap.'),
('shakshuka', 'Şakşuka', 'Shakshuka', 'middle_eastern', '["happy","energetic"]', '[]', 1, 0, 1, 'Domates soslu baharatlı yumurta.', 'Poached eggs in a spicy tomato sauce.'),
('butter_naan', 'Tereyağlı Naan', 'Butter Naan', 'indian', '["happy","relaxed"]', '[]', 1, 0, 0, 'Fırında pişmiş Hint ekmeği.', 'Indian oven-baked flatbread with butter.'),
('samosa', 'Samosa', 'Samosa', 'indian', '["happy","energetic"]', '[]', 1, 1, 0, 'Baharatlı patates ve bezelye dolgulu börek.', 'Fried pastry with spiced potato and pea filling.'),
('miso_soup', 'Miso Çorbası', 'Miso Soup', 'japanese', '["relaxed","tired"]', '[]', 1, 1, 1, 'Geleneksel Japon fermente soya çorbası.', 'Traditional Japanese fermented soybean soup.'),
('edamame', 'Edamame', 'Edamame', 'japanese', '["relaxed","energetic"]', '[]', 1, 1, 1, 'Haşlanmış taze soya fasulyesi.', 'Steamed young soybeans.'),
('gyoza', 'Gyoza', 'Gyoza', 'japanese', '["happy","energetic"]', '[]', 0, 0, 0, 'Japon usulü kızartılmış mantı.', 'Japanese pan-fried dumplings.'),
('laksa', 'Laksa', 'Laksa', 'malaysian', '["happy","tired"]', '[]', 0, 0, 1, 'Baharatlı hindistan cevizi sütlü erişte çorbası.', 'Spicy coconut milk noodle soup.'),
('satay', 'Satay', 'Satay', 'indonesian', '["happy","energetic"]', '[]', 0, 0, 1, 'Izgara et şişleri ve yer fıstığı sosu.', 'Grilled meat skewers with peanut sauce.'),
('gazpacho', 'Gazpacho', 'Gazpacho', 'spanish', '["relaxed","energetic"]', '[]', 1, 1, 1, 'Soğuk İspanyol domates çorbası.', 'Cold Spanish tomato soup.'),
('burrito', 'Burrito', 'Burrito', 'mexican', '["happy","energetic"]', '[]', 0, 0, 0, 'Dürüm arası et, fasulye ve pirinç.', 'Flour tortilla wrap with meat, beans, and rice.'),
('quesadilla', 'Quesadilla', 'Quesadilla', 'mexican', '["happy","relaxed"]', '[]', 1, 0, 0, 'Peynirli ve sebzeli Meksika gözlemesi.', 'Mexican tortilla with cheese and vegetables.'),
('guacamole', 'Guacamole', 'Guacamole', 'mexican', '["happy","relaxed"]', '[]', 1, 1, 1, 'Avokado bazlı Meksika mezesi.', 'Avocado-based Mexican dip.'),
('chimichanga', 'Chimichanga', 'Chimichanga', 'mexican', '["happy","energetic"]', '[]', 0, 0, 0, 'Kızartılmış burrito.', 'Deep-fried burrito.'),
('steak_frites', 'Steak Frites', 'Steak Frites', 'french', '["happy","stressed"]', '[]', 0, 0, 1, 'Izgara biftek ve patates kızartması.', 'Grilled steak and french fries.'),
('croissant', 'Kruvasan', 'Croissant', 'french', '["happy","relaxed"]', '[]', 1, 0, 0, 'Tereyağlı Fransız katmer çöreği.', 'Buttery French flaky pastry.'),
('macarons', 'Makaron', 'Macarons', 'french', '["happy","sad"]', '[]', 1, 0, 1, 'Çeşitli aromalı Fransız kurabiyeleri.', 'French almond meringue-based cookies.'),
('fish_and_chips', 'Balık ve Patates', 'Fish and Chips', 'british', '["happy","tired"]', '[]', 0, 0, 0, 'Pane balık ve patates kızartması.', 'Battered fish and french fries.'),
('shepherds_pie', 'Çoban Turtası', 'Shepherds Pie', 'british', '["sad","tired"]', '[]', 0, 0, 1, 'Kıymalı ve patates püreli fırın yemeği.', 'Minced meat pie topped with mashed potatoes.'),
('pierogi', 'Pierogi', 'Pierogi', 'polish', '["happy","tired"]', '[]', 1, 0, 0, 'Polonya usulü haşlanmış mantı.', 'Polish style boiled dumplings.'),
('borscht', 'Borş Çorbası', 'Borscht', 'russian', '["sad","tired"]', '[]', 1, 1, 1, 'Geleneksel pancar çorbası.', 'Traditional beet soup.'),
('tagine', 'Tajin', 'Tagine', 'moroccan', '["relaxed","happy"]', '[]', 0, 0, 0, 'Fas usulü yavaş pişmiş kuzu veya sebze.', 'Slow-cooked Moroccan meat or vegetable stew.'),
('couscous', 'Kuskus', 'Couscous', 'moroccan', '["happy","relaxed"]', '[]', 1, 1, 0, 'Kuzey Afrika usulü irmik yemeği.', 'North African semolina dish.'),
('jollof_rice', 'Jollof Pilavı', 'Jollof Rice', 'nigerian', '["happy","energetic"]', '[]', 0, 0, 1, 'Baharatlı Batı Afrika pirinç yemeği.', 'Spiced West African rice dish.'),
('acai_bowl', 'Acai Bowl', 'Acai Bowl', 'brazilian', '["energetic","happy"]', '[]', 1, 1, 1, 'Acai meyvesi ve granola ile sağlıklı kase.', 'Healthy bowl with acai berry and granola.'),
('feijoada', 'Feijoada', 'Feijoada', 'brazilian', '["happy","tired"]', '[]', 0, 0, 1, 'Brezilya usulü siyah fasulye ve et yemeği.', 'Brazilian-style black bean and meat stew.'),
('poke_bowl', 'Poke Kasesi', 'Poke Bowl', 'hawaiian', '["energetic","relaxed"]', '[]', 0, 0, 1, 'Hawaii usulü taze balık ve sebze kasesi.', 'Hawaiian fresh raw fish and vegetable bowl.'),
('clam_chowder', 'İstiridye Çorbası', 'Clam Chowder', 'american', '["relaxed","sad"]', '[]', 0, 0, 0, 'Kremalı deniz ürünü çorbası.', 'Creamy seafood soup.'),
('buffalo_wings', 'Buffalo Kanat', 'Buffalo Wings', 'american', '["happy","energetic"]', '[]', 0, 0, 1, 'Acı soslu kızarmış tavuk kanatları.', 'Spicy fried chicken wings.'),
('clam_bake', 'Haşlanmış Deniz Ürünleri', 'Clam Bake', 'american', '["happy","relaxed"]', '[]', 0, 0, 1, 'Çeşitli haşlanmış deniz ürünleri.', 'A variety of steamed seafood.'),
('banh_mi', 'Banh Mi', 'Banh Mi', 'vietnamese', '["happy","energetic"]', '[]', 0, 0, 0, 'Vietnam usulü baget sandviç.', 'Vietnamese baguette sandwich.'),
('tom_yum', 'Tom Yum', 'Tom Yum', 'thai', '["energetic","stressed"]', '[]', 0, 0, 1, 'Acı ve ekşi Tayland çorbası.', 'Spicy and sour Thai soup.'),
('som_tam', 'Som Tam', 'Som Tam', 'thai', '["energetic","relaxed"]', '[]', 1, 1, 1, 'Tayland usulü papaya salatası.', 'Thai-style green papaya salad.'),
('nasi_goreng', 'Nasi Goreng', 'Nasi Goreng', 'indonesian', '["happy","energetic"]', '[]', 0, 0, 0, 'Endonezya usulü kızarmış pirinç.', 'Indonesian fried rice.'),
('peking_duck', 'Pekin Ördeği', 'Peking Duck', 'chinese', '["happy","relaxed"]', '[]', 0, 0, 0, 'Geleneksel Çin çıtır ördek yemeği.', 'Traditional Chinese crispy duck.'),
('hot_pot', 'Hot Pot', 'Hot Pot', 'chinese', '["happy","relaxed"]', '[]', 0, 0, 1, 'Masada pişen çeşitli Çin lezzetleri.', 'A variety of Chinese dishes cooked at the table.'),
('dan_dan_noodles', 'Dan Dan Eriştesi', 'Dan Dan Noodles', 'chinese', '["happy","stressed"]', '[]', 0, 0, 0, 'Baharatlı Çin eriştesi.', 'Spicy Chinese noodles.'),
('dim_sum_selection', 'Dim Sum Seçkisi', 'Dim Sum Selection', 'chinese', '["happy","relaxed"]', '[]', 0, 0, 0, 'Çeşitli Çin mantıları ve atıştırmalıkları.', 'A variety of Chinese dumplings and snacks.');
