-- Massive Enriched Food Data - Batch 4 (Exotic & Global - 100 items)
INSERT INTO foods (id, name_tr, name_en, cuisine, moods, regions, is_vegetarian, is_vegan, is_gluten_free, description_tr, description_en) VALUES
('baba_ganoush_classic', 'Klasik Babagannuş', 'Classic Baba Ganoush', 'middle_eastern', '["relaxed","happy"]', '[]', 1, 1, 1, 'Tahin ve limonlu közlenmiş patlıcan.', 'Classic Levant eggplant dip with tahini and lemon juice.'),
('fattoush_salad', 'Fettuş Salatası', 'Fattoush Salad', 'middle_eastern', '["relaxed","energetic"]', '[]', 1, 1, 0, 'Çıtır ekmekli ve sumaklı Lübnan salatası.', 'Lebanese bread salad with sumac and mixed greens.'),
('knafeh_syrian', 'Suriye Künefesi', 'Syrian Knafeh', 'middle_eastern', '["happy","sad"]', '[]', 1, 0, 0, 'Peynirli ve şerbetli tel kadayıf.', 'Traditional Middle Eastern cheese pastry soaked in syrup.'),
('mansaf_lamb', 'Mansaf', 'Mansaf', 'middle_eastern', '["happy","tired"]', '[]', 0, 0, 1, 'Yoğurt soslu kuzu eti ve pirinç.', 'Jordanian lamb dish cooked in a sauce of fermented dried yogurt.'),
('ful_medames', 'Ful Medames', 'Ful Medames', 'middle_eastern', '["energetic","relaxed"]', '[]', 1, 1, 1, 'Mısır usulü bakla yemeği.', 'Egyptian cooked fava beans served with vegetable oil and cumin.'),
('koshary', 'Kushari', 'Koshary', 'middle_eastern', '["happy","energetic"]', '[]', 1, 1, 0, 'Mısır usulü makarna, pirinç ve mercimek karışımı.', 'Egyptian dish made of rice, macaroni, and lentils.'),
('um_ali', 'Ümmü Ali', 'Um Ali', 'middle_eastern', '["happy","relaxed"]', '[]', 1, 0, 0, 'Mısır usulü sütlü ekmek tatlısı.', 'Egyptian bread pudding with nuts and raisins.'),
('molokhia', 'Mülhiye', 'Molokhia', 'middle_eastern', '["relaxed","happy"]', '[]', 0, 0, 1, 'Jüt yaprağı yahnisi.', 'Middle Eastern soup made from jute mallow leaves.'),
('pabellon_criollo', 'Pabellon Criollo', 'Pabellón Criollo', 'south_american', '["happy","energetic"]', '[]', 0, 0, 1, 'Venezuela usulü et, pirinç ve fasulye.', 'Traditional Venezuelan dish of shredded beef, rice and black beans.'),
('arepa_con_todo', 'Dolu Arepa', 'Arepa with Everything', 'south_american', '["happy","energetic"]', '[]', 0, 0, 1, 'Mısır ekmeği arası çeşitli dolgular.', 'Cornmeal cake stuffed with various fillings from Venezuela/Colombia.'),
('bandeja_paisa', 'Bandeja Paisa', 'Bandeja Paisa', 'south_american', '["happy","tired"]', '[]', 0, 0, 1, 'Kolombiya usulü zengin tabak.', 'Hearty Colombian platter with beans, meat, egg, and avocado.'),
('aji_de_gallina', 'Aji de Gallina', 'Aji de Gallina', 'south_american', '["happy","relaxed"]', '[]', 0, 0, 0, 'Kremalı sarı biberli tavuk yahnisi.', 'Peruvian spicy creamed chicken stew.'),
('anticuchos', 'Anticuchos', 'Anticuchos', 'south_american', '["energetic","happy"]', '[]', 0, 0, 1, 'Izgara kalp şişleri.', 'Traditional Peruvian grilled meat skewers.'),
('chiles_en_nogada', 'Ceviz Soslu Biber', 'Chiles en Nogada', 'mexican', '["happy","relaxed"]', '[]', 0, 0, 1, 'Ceviz soslu ve narlı dolmalık biber.', 'Mexican stuffed poblano peppers with walnut sauce and pomegranate.'),
('mole_poblano', 'Mole Poblano', 'Mole Poblano', 'mexican', '["happy","relaxed"]', '[]', 0, 0, 1, 'Çikolatalı ve baharatlı Meksika soslu tavuk.', 'Chicken in a rich chocolate and chili based sauce.'),
('tamales_corn', 'Mısır Tamales', 'Tamales', 'mexican', '["happy","relaxed"]', '[]', 0, 0, 1, 'Mısır yaprağında buğulanmış hamur.', 'Steamed corn dough filled with meat or cheese in a husk.'),
('cochinita_pibil', 'Cochinita Pibil', 'Cochinita Pibil', 'mexican', '["happy","energetic"]', '[]', 0, 0, 1, 'Yavaş pişmiş narenciyeli domuz eti.', 'Slow-roasted pork marinated in citrus and achiote.'),
('elote_street_corn', 'Meksika Sokak Mısırı', 'Elote', 'mexican', '["happy","energetic"]', '[]', 1, 0, 1, 'Mayonez ve peynirli közlenmiş mısır.', 'Mexican grilled corn on the cob with mayo, cheese, and chili.'),
('pozole_soup', 'Pozole Çorbası', 'Pozole', 'mexican', '["happy","tired"]', '[]', 0, 0, 1, 'Geleneksel mısırlı ve etli çorba.', 'Traditional Mexican soup with hominy and meat.'),
('conch_fritters', 'Deniz Salyangozu Köftesi', 'Conch Fritters', 'caribbean', '["happy","energetic"]', '[]', 0, 0, 0, 'Kızartılmış deniz lezzeti topları.', 'Deep-fried savory balls made with conch meat.'),
('callaloo_stew', 'Callaloo Yahnisi', 'Callaloo', 'caribbean', '["relaxed","happy"]', '[]', 1, 1, 1, 'Yapraklı sebze yahnisi.', 'Leafy green vegetable dish popular in the Caribbean.'),
('roti_curry_goat', 'Keçi Körili Roti', 'Curry Goat with Roti', 'caribbean', '["happy","tired"]', '[]', 0, 0, 0, 'Baharatlı keçi eti ve yassı ekmek.', 'Spicy slow-cooked goat meat served with flatbread.'),
('pelau_rice', 'Pelau Pilavı', 'Pelau', 'caribbean', '["happy","relaxed"]', '[]', 0, 0, 1, 'Etli ve bezelyeli karamelleşmiş pirinç.', 'Trinidadian one-pot rice dish with meat and pigeon peas.'),
('doubles_trinidad', 'Trinidad Doubles', 'Doubles', 'caribbean', '["happy","energetic"]', '[]', 1, 1, 0, 'Nohutlu sokak lezzeti.', 'Popular Trinidadian street food of flatbread and curried chickpeas.'),
('pili_pili_chicken', 'Pili Pili Tavuk', 'Pili Pili Chicken', 'african', '["energetic","happy"]', '[]', 0, 0, 1, 'Çok acı biberli tavuk.', 'Spicy grilled chicken with African bird''s eye chili.'),
('bunny_chow_veg', 'Vejetaryen Bunny Chow', 'Vegetarian Bunny Chow', 'african', '["happy","energetic"]', '[]', 1, 0, 0, 'Ekmek içinde sebze körisi.', 'South African dish of vegetable curry in hollowed out bread.'),
('bobotie', 'Bobotie', 'Bobotie', 'african', '["happy","relaxed"]', '[]', 0, 0, 1, 'Baharatlı kıymalı ve yumurtalı fırın yemeği.', 'South African minced meat dish with an egg-based topping.'),
('chakalaka_and_pap', 'Chakalaka ve Pap', 'Chakalaka & Pap', 'african', '["happy","energetic"]', '[]', 1, 1, 1, 'Acı sebze sosu ve mısır lapası.', 'Spicy vegetable relish served with cornmeal porridge.'),
('nyama_choma', 'Nyama Choma', 'Nyama Choma', 'african', '["happy","energetic"]', '[]', 0, 0, 1, 'Izgara kuzu veya keçi eti.', 'Kenyan style roasted goat or beef meat.'),
('mafe_stew', 'Fıstık Yahnisi', 'Mafe', 'african', '["happy","relaxed"]', '[]', 0, 0, 1, 'Yer fıstığı soslu Batı Afrika yahnisi.', 'West African peanut sauce stew with meat or vegetables.'),
('suya_skewers', 'Suya Şişleri', 'Suya', 'african', '["energetic","happy"]', '[]', 0, 0, 1, 'Baharatlı fıstıklı Nijerya et şişleri.', 'Spicy West African grilled meat skewers coated with peanut spice.'),
('cachupa', 'Cachupa', 'Cachupa', 'african', '["happy","tired"]', '[]', 0, 0, 1, 'Cape Verde usulü mısır ve fasulye yahnisi.', 'Slow-cooked stew of corn, beans, and meat from Cape Verde.'),
('nasi_campur', 'Nasi Campur', 'Nasi Campur', 'indonesian', '["happy","relaxed"]', '[]', 0, 0, 1, 'Karışık Endonezya tabağı.', 'Indonesian rice served with small portions of various other dishes.'),
('bakso_soup', 'Bakso Çorbası', 'Bakso', 'indonesian', '["relaxed","happy"]', '[]', 0, 0, 0, 'Endonezya usulü et topu çorbası.', 'Indonesian meatball soup with noodles and vegetables.'),
('pempek', 'Pempek', 'Pempek', 'indonesian', '["happy","energetic"]', '[]', 0, 0, 0, 'Balık ve tapyoka keki.', 'Savory Indonesian fishcake made of fish and tapioca.'),
('sayur_asem', 'Sayur Asem', 'Sayur Asem', 'indonesian', '["relaxed","energetic"]', '[]', 1, 1, 1, 'Ekşi sebze çorbası.', 'Indonesian tamarind-based vegetable soup.'),
('laksa_sarawak', 'Sarawak Laksa', 'Sarawak Laksa', 'malaysian', '["happy","tired"]', '[]', 0, 0, 1, 'Baharatlı ve fıstıklı erişte çorbası.', 'Spicy Malaysian noodle soup with a complex prawn-based broth.'),
('char_kway_teow', 'Char Kway Teow', 'Char Kway Teow', 'malaysian', '["happy","energetic"]', '[]', 0, 0, 0, 'Kızartılmış yassı pirinç eriştesi.', 'Popular stir-fried flat rice noodles from Malaysia/Singapore.'),
('rendang_daging', 'Dana Rendang', 'Beef Rendang', 'malaysian', '["happy","relaxed"]', '[]', 0, 0, 1, 'Ağır ateşte pişmiş baharatlı dana eti.', 'Traditional slow-cooked beef in coconut milk and spices.'),
('kaya_toast', 'Kaya Tostu', 'Kaya Toast', 'malaysian', '["happy","relaxed"]', '[]', 1, 0, 0, 'Hindistan cevizi reçelli tost.', 'Toast with coconut jam, often served with soft-boiled eggs.'),
('roti_canai', 'Roti Canai', 'Roti Canai', 'malaysian', '["happy","relaxed"]', '[]', 1, 0, 0, 'Çıtır yassı ekmek ve köri sosu.', 'Flatbread served with dhal or curry.'),
('amok_trei', 'Balık Amok', 'Fish Amok', 'cambodian', '["relaxed","happy"]', '[]', 0, 0, 1, 'Hindistan cevizi sütlü buğulanmış balık.', 'Cambodian steamed fish curry in banana leaves.'),
('lok_lak', 'Lok Lak', 'Beef Lok Lak', 'cambodian', '["happy","energetic"]', '[]', 0, 0, 1, 'Soslu sığır eti dilimleri.', 'Stir-fried beef in a lime and black pepper sauce.'),
('adobo_chicken', 'Tavuk Adobo', 'Chicken Adobo', 'filipino', '["happy","relaxed"]', '[]', 0, 0, 1, 'Soya soslu ve sirkeli Filipin klasiği.', 'Chicken braised in soy sauce, vinegar, and garlic.'),
('sinigang_shrimp', 'Karides Sinigang', 'Shrimp Sinigang', 'filipino', '["relaxed","happy"]', '[]', 0, 0, 1, 'Ekşi Filipin çorbası.', 'Sour and savory Filipino soup with tamarind and shrimp.'),
('lechon_pork', 'Lechon', 'Lechon', 'filipino', '["happy","tired"]', '[]', 0, 0, 1, 'Tümden kızarmış süt domuzu.', 'Roasted whole pig, a celebratory dish in the Philippines.'),
('kare_kare', 'Kare-Kare', 'Kare-Kare', 'filipino', '["happy","relaxed"]', '[]', 0, 0, 1, 'Fıstık soslu sığır eti yahnisi.', 'Filipino stew with a rich peanut sauce.'),
('halo_halo', 'Halo-Halo', 'Halo-Halo', 'filipino', '["happy","energetic"]', '[]', 1, 0, 1, 'Karışık Filipin buzlu tatlısı.', 'Mixed cold dessert with crushed ice and various ingredients.'),
('pho_ga', 'Tavuklu Pho', 'Chicken Pho', 'vietnamese', '["relaxed","happy"]', '[]', 0, 0, 1, 'Vietnam usulü tavuklu erişte çorbası.', 'Vietnamese chicken noodle soup.'),
('bun_cha', 'Bun Cha', 'Bun Cha', 'vietnamese', '["happy","energetic"]', '[]', 0, 0, 1, 'Izgara domuz eti ve erişte.', 'Vietnamese grilled pork and noodles served with herbs.'),
('bun_bo_hue', 'Bun Bo Hue', 'Bun Bo Hue', 'vietnamese', '["happy","energetic"]', '[]', 0, 0, 1, 'Acılı Vietnam sığır eti çorbası.', 'Spicy Vietnamese beef noodle soup from Hue region.'),
('banh_mi_pork', 'Domuz Etli Banh Mi', 'Pork Banh Mi', 'vietnamese', '["happy","energetic"]', '[]', 0, 0, 0, 'Geleneksel Vietnam sandviçi.', 'Traditional Vietnamese baguette sandwich with grilled pork.'),
('goi_cuon', 'Goi Cuon', 'Goi Cuon', 'vietnamese', '["energetic","relaxed"]', '[]', 0, 0, 1, 'Karidesli taze pirinç rulosu.', 'Translucent spring rolls with shrimp, pork, and herbs.'),
('bulgogi_beef', 'Dana Bulgogi', 'Beef Bulgogi', 'korean', '["happy","energetic"]', '[]', 0, 0, 1, 'Kore usulü marineli ızgara sığır eti.', 'Korean-style marinated grilled thin slices of beef.'),
('kimchi_jjigae', 'Kimchi Yahnisi', 'Kimchi Jjigae', 'korean', '["happy","energetic"]', '[]', 0, 0, 1, 'Acı kimchi çorbası.', 'Spicy Korean stew made with kimchi and other ingredients.'),
('japchae', 'Japchae', 'Japchae', 'korean', '["relaxed","happy"]', '[]', 1, 1, 1, 'Kore usulü cam erişte ve sebze.', 'Sweet and savory stir-fried glass noodles with vegetables.'),
('tteokbokki', 'Tteokbokki', 'Tteokbokki', 'korean', '["happy","energetic"]', '[]', 1, 0, 0, 'Acı soslu pirinç kekleri.', 'Spicy stir-fried rice cakes, a popular Korean street food.'),
('kimbap', 'Kimbap', 'Kimbap', 'korean', '["happy","energetic"]', '[]', 1, 0, 1, 'Kore usulü pirinç ruloları.', 'Korean dish made from cooked rice and other ingredients rolled in sea weed.'),
('pancit_bihon', 'Pancit Bihon', 'Pancit Bihon', 'filipino', '["happy","relaxed"]', '[]', 0, 0, 1, 'Pirinç erişteli Filipin yemeği.', 'Filipino stir-fried rice noodles with meat and vegetables.'),
('lumpia_shanghai', 'Lumpia Shanghai', 'Lumpia Shanghai', 'filipino', '["happy","energetic"]', '[]', 0, 0, 0, 'Filipin usulü mini kızarmış börekler.', 'Crispy Filipino spring rolls filled with ground meat.'),
('dinuguan', 'Dinuguan', 'Dinuguan', 'filipino', '["happy","tired"]', '[]', 0, 0, 1, 'Filipin usulü kan yahnisi.', 'Filipino savory stew typically of pork offal simmered in blood.'),
('balut_egg', 'Balut', 'Balut', 'filipino', '["energetic","happy"]', '[]', 0, 0, 1, 'Gelişmiş ördek embriyosu yumurtası.', 'Developing bird embryo that is boiled and eaten from the shell.'),
('gravlax_salmon', 'Gravlax Somon', 'Gravlax', 'nordic', '["relaxed","happy"]', '[]', 0, 0, 1, 'Dereotlu ve tuzlu marineli somon.', 'Nordic dish of dry-cured salmon marinated in salt, sugar, and dill.'),
('swedish_meatballs', 'İsveç Köftesi', 'Swedish Meatballs', 'nordic', '["happy","relaxed"]', '[]', 0, 0, 0, 'Kremalı soslu İsveç köfteleri.', 'Classic meatballs served with a creamy gravy and lingonberry jam.'),
('smørrebrød', 'Açık Sandviç', 'Smørrebrød', 'nordic', '["happy","relaxed"]', '[]', 0, 0, 0, 'Danimarka usulü zengin açık sandviç.', 'Danish open-faced sandwich on rye bread with various toppings.'),
('raggmunk', 'Patates Krebi (İsveç)', 'Raggmunk', 'nordic', '["happy","tired"]', '[]', 1, 0, 0, 'İsveç usulü patates krebi.', 'Swedish potato pancakes often served with fried bacon.'),
('fiskesuppe', 'Norveç Balık Çorbası', 'Fiskesuppe', 'nordic', '["relaxed","happy"]', '[]', 0, 0, 1, 'Kremalı lezzetli balık çorbası.', 'Creamy Norwegian fish soup with vegetables and fresh fish.'),
('pytt_i_panna', 'Pytt i Panna', 'Pytt i Panna', 'nordic', '["happy","tired"]', '[]', 0, 0, 1, 'İsveç usulü kavrulmuş patates ve et.', 'Swedish "small pieces in a pan" - diced potatoes, meat, and onions.'),
('gravy_poutine', 'Klasik Poutine', 'Classic Poutine', 'canadian', '["happy","sad"]', '[]', 1, 0, 0, 'Peynir ve yoğun soslu patates.', 'Quebecois dish of fries topped with cheese curds and gravy.'),
('butter_tart', 'Tereyağlı Tart', 'Butter Tart', 'canadian', '["happy","sad"]', '[]', 1, 0, 0, 'Kanada usulü tatlı tart.', 'Traditional Canadian sweet pastry with a flaky crust and gooey center.'),
('nanaimo_bar', 'Nanaimo Bar', 'Nanaimo Bar', 'canadian', '["happy","sad"]', '[]', 1, 0, 0, 'Üç katmanlı Kanada tatlısı.', 'No-bake dessert bar from Canada with a crumb base and custard icing.'),
('tourtiere', 'Kanada Etli Turtası', 'Tourtière', 'canadian', '["happy","tired"]', '[]', 0, 0, 0, 'Geleneksel Kanada etli turtası.', 'French-Canadian meat pie usually made with minced pork or beef.'),
('bannock_bread', 'Bannock Ekmeği', 'Bannock', 'canadian', '["relaxed","happy"]', '[]', 1, 1, 0, 'Geleneksel yerli ekmeği.', 'Traditional Indigenous flatbread found across North America.'),
('clam_chowder_ne', 'New England İstiridye Çorbası', 'New England Clam Chowder', 'american', '["relaxed","sad"]', '[]', 0, 0, 0, 'Beyaz kremalı deniz ürünü çorbası.', 'Creamy clam chowder with potatoes and onions.'),
('jambalaya_cajun', 'Jambalaya', 'Jambalaya', 'american', '["happy","energetic"]', '[]', 0, 0, 1, 'Baharatlı pirinç ve et yemeği.', 'Louisiana-born dish of Creole origin with rice, meat, and vegetables.'),
('gumbo_stew', 'Gumbo Yahnisi', 'Gumbo', 'american', '["happy","relaxed"]', '[]', 0, 0, 0, 'Koyu kıvamlı Louisiana yahnisi.', 'Stew popular in the U.S. state of Louisiana with meat or shellfish.'),
('philly_cheesesteak', 'Philly Peynirli Sandviç', 'Philly Cheesesteak', 'american', '["happy","energetic"]', '[]', 0, 0, 0, 'Etli ve erimiş peynirli sandviç.', 'Thinly sliced beef and melted cheese in a long hoagie roll.'),
('bbq_ribs_smoked', 'Tütsülenmiş Kaburga', 'Smoked BBQ Ribs', 'american', '["happy","relaxed"]', '[]', 0, 0, 1, 'Amerikan usulü yavaş pişmiş kaburga.', 'Slow-cooked pork or beef ribs with a smoky barbecue glaze.'),
('cornbread_classic', 'Klasik Mısır Ekmeği', 'Classic Cornbread', 'american', '["happy","relaxed"]', '[]', 1, 0, 0, 'Amerikan usulü tatlı-tuzlu mısır ekmeği.', 'Traditional Southern US flatbread made with cornmeal.'),
('reuben_sandwich', 'Reuben Sandviçi', 'Reuben Sandwich', 'american', '["happy","energetic"]', '[]', 0, 0, 0, 'Etli ve lahana turşulu sandviç.', 'Grilled sandwich with corned beef, Swiss cheese, and sauerkraut.'),
('key_lime_pie', 'Limonlu Turta', 'Key Lime Pie', 'american', '["happy","relaxed"]', '[]', 1, 0, 0, 'Florida usulü ekşi-tatlı turta.', 'American dessert made of key lime juice, egg yolks, and condensed milk.'),
('chicken_and_waffles', 'Tavuk ve Waffle', 'Chicken and Waffles', 'american', '["happy","energetic"]', '[]', 0, 0, 0, 'Kızarmış tavuk ve şuruplu waffle.', 'Crispy fried chicken served on top of fluffy waffles.'),
('deep_dish_pizza', 'Chicago Derin Pizza', 'Chicago Deep Dish Pizza', 'american', '["happy","tired"]', '[]', 0, 0, 0, 'Kalın ve bol malzemeli pizza.', 'Pizza with a thick, deep crust containing large amounts of toppings.'),
('lobster_roll_maine', 'Istakoz Rulosu', 'Lobster Roll', 'american', '["happy","relaxed"]', '[]', 0, 0, 0, 'Istakoz etli lüks sandviç.', 'Lobster meat served in a buttered and toasted bun.'),
('buffalo_cauliflower', 'Buffalo Karnabahar', 'Buffalo Cauliflower', 'american', '["happy","energetic"]', '[]', 1, 1, 1, 'Acı soslu çıtır karnabahar.', 'Roasted cauliflower bites tossed in spicy buffalo sauce.'),
('crab_cakes_maryland', 'Yengeç Köftesi', 'Maryland Crab Cakes', 'american', '["happy","relaxed"]', '[]', 0, 0, 0, 'Baharatlı ve bol yengeçli köfte.', 'Fried or baked patties made from crab meat and seasonings.'),
('southern_fried_chicken', 'Güney Usulü Kızarmış Tavuk', 'Southern Fried Chicken', 'american', '["happy","energetic"]', '[]', 0, 0, 0, 'Baharatlı ve çıtır tavuk.', 'Chicken pieces coated in seasoned flour or batter and pan-fried.'),
('hush_puppies', 'Mısır Hamuru Topları', 'Hush Puppies', 'american', '["happy","relaxed"]', '[]', 1, 0, 0, 'Kızartılmış mısır unu topları.', 'Deep-fried balls made from cornmeal-based batter.'),
('pecan_pie', 'Pekanya Cevizli Turta', 'Pecan Pie', 'american', '["happy","sad"]', '[]', 1, 0, 0, 'Tatlı ve yoğun cevizli turta.', 'Sweet pie made primarily with corn syrup and pecan nuts.'),
('clam_dip_creamy', 'Kremalı İstiridye Mezesi', 'Creamy Clam Dip', 'american', '["happy","relaxed"]', '[]', 0, 0, 1, 'Cipslerle servis edilen deniz ürünü mezesi.', 'Savory dip made from chopped clams, cream cheese, and spices.'),
('pot_roast_beef', 'Fırın Biftek', 'Pot Roast', 'american', '["happy","tired"]', '[]', 0, 0, 1, 'Yavaş pişmiş sebzeli dana eti.', 'Beef dish made by slow-cooking a tough cut of meat.'),
('meatloaf_classic', 'Klasik Rulo Köfte', 'Classic Meatloaf', 'american', '["relaxed","happy"]', '[]', 0, 0, 0, 'Amerikan usulü rulo et yemeği.', 'Baked loaf made from ground meat mixed with other ingredients.'),
('egg_salad_sandwich', 'Yumurta Salatalı Sandviç', 'Egg Salad Sandwich', 'american', '["relaxed","happy"]', '[]', 1, 0, 0, 'Kremalı yumurta salatası tabağı.', 'Sandwich filled with a mixture of hard-boiled eggs and mayo.'),
('biscuit_and_gravy', 'Bisküvi ve Sos', 'Biscuits and Gravy', 'american', '["happy","tired"]', '[]', 0, 0, 0, 'Yumuşak bisküvi ve sosisli beyaz sos.', 'Soft dough biscuits covered in thick country or white gravy.'),
('corn_chowder_creamy', 'Mısır Çorbası', 'Corn Chowder', 'american', '["relaxed","happy"]', '[]', 1, 0, 1, 'Yoğun kıvamlı kremalı mısır çorbası.', 'Thick and creamy soup made with fresh corn and vegetables.'),
('bananas_foster', 'Muzlu Foster', 'Bananas Foster', 'american', '["happy","sad"]', '[]', 1, 0, 1, 'Karamelli ve dondurmalı muz tatlısı.', 'Dessert made from bananas and vanilla ice cream with butter and brown sugar sauce.'),
('mississippi_mud_pie', 'Mississippi Mud Turtası', 'Mississippi Mud Pie', 'american', '["happy","sad"]', '[]', 1, 0, 0, 'Bol çikolatalı ve yoğun tatlı.', 'Chocolate-based dessert pie with a gooey chocolate sauce layer.'),
('shrimp_grits', 'Karides ve Mısır Lapası', 'Shrimp and Grits', 'american', '["happy","relaxed"]', '[]', 0, 0, 1, 'Izgara karides ve kremsi mısır lapası.', 'Traditional Southern US dish of sauteed shrimp over stone-ground grits.'),
('nashville_hot_chicken', 'Nashville Acı Tavuğu', 'Nashville Hot Chicken', 'american', '["happy","energetic"]', '[]', 0, 0, 0, 'Ekstra acı kaplamalı kızarmış tavuk.', 'Fried chicken with a major kick from cayenne pepper.');
