-- Massive Enriched Food Data - Batch 2 (Global Diversity - 100 items)
INSERT INTO foods (id, name_tr, name_en, cuisine, moods, regions, is_vegetarian, is_vegan, is_gluten_free, description_tr, description_en) VALUES
('sushi_platter', 'Suşi Tabağı', 'Sushi Platter', 'japanese', '["happy","relaxed"]', '[]', 0, 0, 1, 'Çeşitli nigiri ve maki suşiler.', 'Assorted nigiri and maki sushi.'),
('tempura_shrimp', 'Karides Tempura', 'Shrimp Tempura', 'japanese', '["happy","energetic"]', '[]', 0, 0, 0, 'Çıtır Japon usulü kızartılmış karides.', 'Crispy Japanese style fried shrimp.'),
('okonomiyaki', 'Okonomiyaki', 'Okonomiyaki', 'japanese', '["happy","relaxed"]', '[]', 0, 0, 0, 'Japon usulü lahana ve deniz ürünü krebi.', 'Japanese savory pancake with cabbage and seafood.'),
('yakisoba', 'Yakisoba', 'Yakisoba', 'japanese', '["happy","energetic"]', '[]', 0, 0, 0, 'Japon usulü kızartılmış erişte.', 'Japanese stir-fried noodles.'),
('tonkatsu', 'Tonkatsu', 'Tonkatsu', 'japanese', '["happy","tired"]', '[]', 0, 0, 0, 'Japon usulü pane domuz veya tavuk pirzola.', 'Japanese breaded and deep-fried cutlet.'),
('unagi_don', 'Unagi Don', 'Unagi Don', 'japanese', '["happy","relaxed"]', '[]', 0, 0, 0, 'Izgara yılan balıklı pirinç tabağı.', 'Grilled eel over rice.'),
('miso_ramen', 'Miso Ramen', 'Miso Ramen', 'japanese', '["happy","tired"]', '[]', 0, 0, 0, 'Miso bazlı zengin ramen çorbası.', 'Rich ramen noodle soup in miso broth.'),
('shoyu_ramen', 'Shoyu Ramen', 'Shoyu Ramen', 'japanese', '["happy","tired"]', '[]', 0, 0, 0, 'Soya soslu ramen çorbası.', 'Ramen noodle soup in soy sauce broth.'),
('green_curry', 'Thai Yeşil Köri', 'Thai Green Curry', 'thai', '["happy","energetic"]', '[]', 0, 0, 1, 'Hindistan cevizi sütlü acı yeşil köri.', 'Spicy green curry with coconut milk.'),
('red_curry', 'Thai Kırmızı Köri', 'Thai Red Curry', 'thai', '["happy","energetic"]', '[]', 0, 0, 1, 'Kurutulmuş kırmızı biberli Thai körisi.', 'Spicy Thai red curry with coconut milk.'),
('massaman_curry', 'Massaman Köri', 'Massaman Curry', 'thai', '["happy","relaxed"]', '[]', 0, 0, 1, 'Fıstıklı ve patatesli hafif Thai körisi.', 'Mild Thai curry with peanuts and potatoes.'),
('papaya_salad', 'Papaya Salatası', 'Papaya Salad', 'thai', '["energetic","relaxed"]', '[]', 1, 1, 1, 'Acı ve ekşi taze papaya salatası.', 'Spicy and sour green papaya salad.'),
('mango_sticky_rice', 'Mangolu Yapışkan Pirinç', 'Mango Sticky Rice', 'thai', '["happy","relaxed"]', '[]', 1, 1, 1, 'Hindistan cevizi sütlü tatlı pirinç ve mango.', 'Sweet sticky rice with coconut milk and fresh mango.'),
('satay_chicken', 'Tavuk Satay', 'Chicken Satay', 'indonesian', '["happy","energetic"]', '[]', 0, 0, 1, 'Izgara tavuk şişleri ve fıstık sosu.', 'Grilled chicken skewers with peanut sauce.'),
('gado_gado', 'Gado-Gado', 'Gado-Gado', 'indonesian', '["relaxed","energetic"]', '[]', 1, 0, 1, 'Yer fıstığı soslu haşlanmış sebze salatası.', 'Boiled vegetable salad with peanut sauce.'),
('rendang', 'Beef Rendang', 'Beef Rendang', 'malaysian', '["happy","relaxed"]', '[]', 0, 0, 1, 'Yavaş pişmiş acı ve baharatlı sığır eti.', 'Slow-cooked spicy beef in coconut milk.'),
('hainanese_chicken_rice', 'Hainan Tavuklu Pirinç', 'Hainanese Chicken Rice', 'chinese', '["relaxed","happy"]', '[]', 0, 0, 0, 'Haşlanmış tavuk ve aromalı pirinç.', 'Poached chicken served with seasoned rice.'),
('kung_pao_chicken', 'Kung Pao Tavuk', 'Kung Pao Chicken', 'chinese', '["happy","energetic"]', '[]', 0, 0, 0, 'Fıstıklı ve acı biberli tavuk.', 'Spicy stir-fried chicken with peanuts and chili.'),
('mapo_tofu', 'Mapo Tofu', 'Mapo Tofu', 'chinese', '["happy","energetic"]', '[]', 1, 1, 0, 'Baharatlı soslu tofu yemeği.', 'Spicy Sichuan tofu dish.'),
('spring_rolls', 'Sebzeli Çin Böreği', 'Spring Rolls', 'chinese', '["happy","energetic"]', '[]', 1, 1, 0, 'Çıtır sebzeli rulo börekler.', 'Crispy vegetable stuffed rolls.'),
('wonton_soup', 'Wonton Çorbası', 'Wonton Soup', 'chinese', '["relaxed","tired"]', '[]', 0, 0, 0, 'Çin mantılı berrak çorba.', 'Clear soup with Chinese dumplings.'),
('tandoori_chicken', 'Tandoori Tavuk', 'Tandoori Chicken', 'indian', '["happy","energetic"]', '[]', 0, 0, 1, 'Yoğurtlu baharatlı közlenmiş tavuk.', 'Spiced chicken roasted in a clay oven.'),
('chicken_tikka_masala', 'Tavuk Tikka Masala', 'Chicken Tikka Masala', 'indian', '["happy","relaxed"]', '[]', 0, 0, 1, 'Kremalı baharatlı tavuk yemeği.', 'Roasted chicken chunks in a spicy creamy sauce.'),
('palak_paneer', 'Palak Paneer', 'Palak Paneer', 'indian', '["relaxed","happy"]', '[]', 1, 0, 1, 'Ispanaklı ve peynirli Hint yemeği.', 'Spinach puree with paneer cheese.'),
('chana_masala', 'Chana Masala', 'Chana Masala', 'indian', '["happy","energetic"]', '[]', 1, 1, 1, 'Baharatlı nohut tabağı.', 'Spicy chickpea curry.'),
('biryani_lamb', 'Kuzu Etli Biryani', 'Lamb Biryani', 'indian', '["happy","relaxed"]', '[]', 0, 0, 1, 'Baharatlı aromalı etli pirinç.', 'Aromatic spiced rice with lamb.'),
('dal_makhani', 'Dal Makhani', 'Dal Makhani', 'indian', '["relaxed","happy"]', '[]', 1, 0, 1, 'Karamelize edilmiş mercimek ve fasulye.', 'Slow-cooked black lentils and kidney beans.'),
('gulab_jamun', 'Gulab Jamun', 'Gulab Jamun', 'indian', '["happy","sad"]', '[]', 1, 0, 0, 'Sütlü Hint tatlısı topları.', 'Deep fried milk solid balls in syrup.'),
('falafel_bowl', 'Falafel Kasesi', 'Falafel Bowl', 'middle_eastern', '["energetic","happy"]', '[]', 1, 1, 1, 'Falafel, humus ve sebze dolu kase.', 'Bowl with falafel, hummus and fresh greens.'),
('tabbouleh', 'Tabule', 'Tabbouleh', 'middle_eastern', '["relaxed","energetic"]', '[]', 1, 1, 0, 'Maydanoz ve bulgur salatası.', 'Levantine parsley and bulgur salad.'),
('kibbeh', 'İçli Köfte (Ortadoğu)', 'Kibbeh', 'middle_eastern', '["happy","relaxed"]', '[]', 0, 0, 0, 'Kızartılmış etli bulgur köftesi.', 'Deep-fried bulgur crust stuffed with minced meat.'),
('mandi_rice', 'Mandi Pilavı', 'Mandi', 'middle_eastern', '["happy","relaxed"]', '[]', 0, 0, 1, 'Geleneksel tütsülenmiş etli pirinç.', 'Traditional Yemeni meat and rice dish.'),
('baklava_pistachio', 'Fıstıklı Baklava', 'Pistachio Baklava', 'middle_eastern', '["happy","sad"]', '[]', 1, 0, 0, 'Fıstıklı kat kat şerbetli tatlı.', 'Layered pastry with pistachios and syrup.'),
('lasagna', 'Lazanya', 'Lasagna', 'italian', '["happy","tired"]', '[]', 0, 0, 0, 'Etli ve peynirli katlı makarna.', 'Layered pasta with meat and cheese.'),
('risotto_mushroom', 'Mantarlı Risotto', 'Mushroom Risotto', 'italian', '["relaxed","happy"]', '[]', 1, 0, 1, 'Kremalı mantarlı pirinç yemeği.', 'Creamy rice dish with mushrooms.'),
('bruschetta', 'Bruschetta', 'Bruschetta', 'italian', '["happy","relaxed"]', '[]', 1, 1, 0, 'Domatesli ve sarımsaklı kızarmış ekmek.', 'Grilled bread topped with tomato and garlic.'),
('gnocchi_pesto', 'Pesto Soslu Gnocchi', 'Gnocchi with Pesto', 'italian', '["relaxed","happy"]', '[]', 1, 0, 0, 'Patates makarnası ve fesleğen sosu.', 'Potato dumplings with basil pesto.'),
('calzone', 'Calzone', 'Calzone', 'italian', '["happy","energetic"]', '[]', 0, 0, 0, 'Kapalı pizza.', 'Folded pizza.'),
('osso_buco', 'Osso Buco', 'Osso Buco', 'italian', '["happy","tired"]', '[]', 0, 0, 1, 'Sebzeli dana incik.', 'Braised veal shanks with vegetables.'),
('panna_cotta', 'Panna Cotta', 'Panna Cotta', 'italian', '["happy","relaxed"]', '[]', 1, 0, 1, 'İtalyan sütlü jöle tatlısı.', 'Italian cooked cream dessert.'),
('cassoulet', 'Cassoulet', 'Cassoulet', 'french', '["happy","tired"]', '[]', 0, 0, 1, 'Zengin fasulye ve et yahnisi.', 'Rich slow-cooked bean and meat casserole.'),
('quiche_lorraine', 'Kiş Loren', 'Quiche Lorraine', 'french', '["happy","relaxed"]', '[]', 0, 0, 0, 'Peynirli ve pastırmalı tuzlu kek.', 'Savory open tart with cheese and bacon.'),
('bouillabaisse', 'Bouillabaisse', 'Bouillabaisse', 'french', '["happy","relaxed"]', '[]', 0, 0, 1, 'Zengin deniz ürünleri çorbası.', 'Traditional Provencal fish stew.'),
('coq_au_vin', 'Şarap Soslu Tavuk', 'Coq au Vin', 'french', '["happy","relaxed"]', '[]', 0, 0, 1, 'Şarap ve mantarlı tavuk yahnisi.', 'Chicken braised with wine and mushrooms.'),
('crepe_suzette', 'Krep Süzet', 'Crepe Suzette', 'french', '["happy","sad"]', '[]', 1, 0, 0, 'Portakal soslu krep.', 'French dessert of crepes in orange sauce.'),
('souffle_chocolate', 'Çikolatalı Sufle', 'Chocolate Souffle', 'french', '["happy","sad"]', '[]', 1, 0, 0, 'Sıcak akışkan çikolatalı sufle.', 'Baked egg-based chocolate dessert.'),
('tapas_selection', 'Tapas Tabağı', 'Tapas Selection', 'spanish', '["happy","energetic"]', '[]', 0, 0, 0, 'Çeşitli küçük İspanyol mezeleri.', 'A variety of small Spanish appetizers.'),
('tortilla_espanola', 'İspanyol Omleti', 'Spanish Tortilla', 'spanish', '["happy","relaxed"]', '[]', 1, 0, 1, 'Patatesli ve soğanlı omlet.', 'Traditional Spanish omelet with potatoes.'),
('churros', 'Churros', 'Churros', 'spanish', '["happy","sad"]', '[]', 1, 0, 0, 'Çikolata soslu kızarmış hamur.', 'Fried dough pastry with chocolate dip.'),
('patatas_bravas', 'Patatas Bravas', 'Patatas Bravas', 'spanish', '["happy","energetic"]', '[]', 1, 1, 1, 'Acı soslu kızarmış patates tabağı.', 'Fried potatoes with spicy tomato sauce.'),
('weiner_schnitzel', 'Viyana Şinitzeli', 'Wiener Schnitzel', 'austrian', '["happy","tired"]', '[]', 0, 0, 0, 'Geleneksel ince pane edilmiş et.', 'Traditional thin breaded pan-fried veal.'),
('apfelstrudel', 'Elmalı Turta', 'Apple Strudel', 'austrian', '["happy","relaxed"]', '[]', 1, 0, 0, 'Viyana usulü elmalı tatlı.', 'Traditional Viennese apple pastry.'),
('fish_tacos', 'Balıklı Taco', 'Fish Tacos', 'mexican', '["happy","energetic"]', '[]', 0, 0, 1, 'Taze balıklı ve sebzeli taco.', 'Tacos filled with fresh fish and slaw.'),
('enchiladas', 'Enchiladas', 'Enchiladas', 'mexican', '["happy","energetic"]', '[]', 0, 0, 0, 'Soslu ve peynirli dürüm rulosu.', 'Corn tortillas rolled around a filling and covered with sauce.'),
('ceviche_peru', 'Peru Ceviche', 'Peruvian Ceviche', 'peruvian', '["energetic","relaxed"]', '[]', 0, 0, 1, 'Misket limonu ile marine edilmiş balık.', 'Fresh raw fish cured in citrus juices and chili.'),
('lomo_saltado', 'Lomo Saltado', 'Lomo Saltado', 'peruvian', '["happy","energetic"]', '[]', 0, 0, 0, 'Sığır eti ve patatesli stir-fry.', 'Peruvian stir-fried beef with onions and potatoes.'),
('empanadas', 'Empanadas', 'Empanadas', 'argentinian', '["happy","energetic"]', '[]', 0, 0, 0, 'Etli veya peynirli kızarmış börek.', 'Baked or fried turnover filled with meat or cheese.'),
('asado_beef', 'Arjantin Barbekü', 'Asado', 'argentinian', '["happy","relaxed"]', '[]', 0, 0, 1, 'Izgara bol et tabağı.', 'Traditional Argentinian barbecue.'),
('pão_de_queijo', 'Peynirli Ekmek', 'Cheese Bread', 'brazilian', '["happy","relaxed"]', '[]', 1, 0, 1, 'Brezilya usulü küçük peynirli ekmekler.', 'Small, baked cheese rolls from Brazil.'),
('brigadeiro', 'Brigadeiro', 'Brigadeiro', 'brazilian', '["happy","sad"]', '[]', 1, 0, 1, 'Brezilya usulü çikolatalı toplar.', 'Brazilian chocolate truffles.'),
('jerk_chicken', 'Jerk Tavuk', 'Jerk Chicken', 'caribbean', '["happy","energetic"]', '[]', 0, 0, 1, 'Baharatlı Karayip usulü tavuk.', 'Spicy Caribbean style grilled chicken.'),
('ackee_and_saltfish', 'Ackee ve Tuzlu Balık', 'Ackee and Saltfish', 'caribbean', '["happy","energetic"]', '[]', 0, 0, 1, 'Jamaika usulü meyve ve balık tabağı.', 'Jamaica''s national dish of sauteed fruit and saltfish.'),
('moti_roti', 'Moti Roti', 'Roti', 'caribbean', '["happy","relaxed"]', '[]', 1, 1, 0, 'Karayip usulü yassı ekmek.', 'Caribbean soft flatbread.'),
('plantain_fry', 'Kızarmış Muz', 'Fried Plantains', 'african', '["happy","relaxed"]', '[]', 1, 1, 1, 'Kızartılmış tatlı muz dilimleri.', 'Sweet fried plantain slices.'),
('egusi_soup', 'Egusi Çorbası', 'Egusi Soup', 'african', '["happy","relaxed"]', '[]', 0, 0, 1, 'Kavun çekirdekli Nijerya yahnisi.', 'Nigerian stew made with melon seeds.'),
('fufu_and_light_soup', 'Fufu ve Hafif Çorba', 'Fufu and Soup', 'african', '["happy","tired"]', '[]', 0, 0, 1, 'Geleneksel Batı Afrika hamur yemeği.', 'Traditional West African dough-like food with soup.'),
('injera_platter', 'Etiyopya Tabağı', 'Injera Platter', 'african', '["happy","relaxed"]', '[]', 1, 1, 0, 'Injera ekmeği ve çeşitli sebze yahnileri.', 'Ethiopian flatbread with various stews.'),
('biltong', 'Biltong', 'Biltong', 'african', '["energetic","happy"]', '[]', 0, 0, 1, 'Güney Afrika usulü kurutulmuş et.', 'South African dried, cured meat.'),
('bunny_chow', 'Bunny Chow', 'Bunny Chow', 'african', '["happy","energetic"]', '[]', 0, 0, 0, 'Ekmek içinde köri yemeği.', 'South African fast food of curry in a hollowed bread loaf.'),
('shish_tawok', 'Şiş Tavuk', 'Shish Tawok', 'middle_eastern', '["happy","energetic"]', '[]', 0, 0, 1, 'Lübnan usulü yoğurtlu tavuk şiş.', 'Lebanese style marinated chicken skewers.'),
('manakish', 'Manakiş', 'Manakish', 'middle_eastern', '["happy","relaxed"]', '[]', 1, 0, 0, 'Zahterli ve peynirli Ortadoğu pidesi.', 'Middle Eastern flatbread with za''atar or cheese.'),
('fatayer', 'Fatayer', 'Fatayer', 'middle_eastern', '["happy","relaxed"]', '[]', 1, 0, 0, 'Ispanaklı veya peynirli küçük börekler.', 'Middle Eastern meat or spinach meat pie/pantry.'),
('halloumi_grill', 'Izgara Hellim', 'Grilled Halloumi', 'middle_eastern', '["happy","relaxed"]', '[]', 1, 0, 1, 'Izgara Kıbrıs peyniri.', 'Grilled Cypriot halloumi cheese.'),
('moussaka_eggplant', 'Patlıcanlı Musakka', 'Eggplant Moussaka', 'greek', '["happy","tired"]', '[]', 0, 0, 0, 'Yunan usulü patlıcan ve beşamel soslu.', 'Greek style eggplant and bechamel bake.'),
('souvlaki', 'Souvlaki', 'Souvlaki', 'greek', '["happy","energetic"]', '[]', 0, 0, 1, 'Geleneksel Yunan et şişleri.', 'Greek fast food of small pieces of meat on a skewer.'),
('gyro_wrap', 'Gyro Dürüm', 'Gyro Wrap', 'greek', '["happy","energetic"]', '[]', 0, 0, 0, 'Pita ekmeğinde et ve cacık.', 'Greek meat cooked on a vertical rotisserie in pita.'),
('spanakopita', 'Ispanaklı Turta', 'Spanakopita', 'greek', '["happy","relaxed"]', '[]', 1, 0, 0, 'Ispanaklı ve peynirli çıtır börek.', 'Greek spinach and feta pie in phyllo pastry.'),
('baklava_greek', 'Yunan Baklavası', 'Greek Baklava', 'greek', '["happy","sad"]', '[]', 1, 0, 0, 'Cevizli ve tarçınlı şerbetli tatlı.', 'Greek layered pastry with walnuts and cinnamon.'),
('kottu_roti', 'Kottu Roti', 'Kottu Roti', 'sri_lankan', '["happy","energetic"]', '[]', 0, 0, 0, 'Doğranmış ekmek ve sebze stir-fry.', 'Sri Lankan dish of chopped roti, vegetables and spices.'),
('hoppers', 'Hoppers', 'Hoppers', 'sri_lankan', '["happy","relaxed"]', '[]', 1, 1, 1, 'Kase şeklinde pirinç unu krebi.', 'Sri Lankan bowl-shaped pancakes.'),
('laksa_soup', 'Laksa Çorbası', 'Laksa', 'malaysian', '["happy","tired"]', '[]', 0, 0, 0, 'Baharatlı hindistan cevizi sütlü çorba.', 'Spicy noodle soup based on coconut milk.'),
('nasi_lemak', 'Nasi Lemak', 'Nasi Lemak', 'malaysian', '["happy","relaxed"]', '[]', 0, 0, 1, 'Hindistan cevizi sütlü pirinç ve garnitürler.', 'Malaysian coconut milk rice with various sides.'),
('pho_bo', 'Dana Etli Pho', 'Beef Pho', 'vietnamese', '["relaxed","happy"]', '[]', 0, 0, 1, 'Vietnam usulü aromalı dana eti çorbası.', 'Vietnamese aromatic beef noodle soup.'),
('summer_rolls', 'Taze Bahar Böreği', 'Summer Rolls', 'vietnamese', '["energetic","relaxed"]', '[]', 1, 1, 1, 'Taze sebzeli şeffaf pirinç rulosu.', 'Fresh rice paper rolls with vegetables and herbs.'),
('banh_xeo', 'Banh Xeo', 'Banh Xeo', 'vietnamese', '["happy","energetic"]', '[]', 0, 0, 1, 'Vietnam usulü çıtır krep.', 'Vietnamese savory sizzling crepe.'),
('hainanese_chicken', 'Hainan Tavuğu', 'Hainanese Chicken', 'chinese', '["relaxed","happy"]', '[]', 0, 0, 1, 'Haşlanmış yumuşak tavuk.', 'Poached chicken with ginger and scallion sauce.'),
('dim_sum_mix', 'Karışık Dim Sum', 'Dim Sum Mix', 'chinese', '["happy","relaxed"]', '[]', 0, 0, 0, 'Buharda pişmiş çeşitli Çin atıştırmalıkları.', 'Assorted steamed Chinese dumplings.'),
('kung_pao_shrimp', 'Kung Pao Karides', 'Kung Pao Shrimp', 'chinese', '["happy","energetic"]', '[]', 0, 0, 0, 'Acılı ve fıstıklı karides.', 'Spicy stir-fried shrimp with peanuts.'),
('scallion_pancake', 'Taze Soğanlı Krep', 'Scallion Pancake', 'chinese', '["happy","relaxed"]', '[]', 1, 1, 0, 'Çıtır Çin usulü soğanlı gözleme.', 'Chinese savory unleavened flatbread with scallions.'),
('hot_and_sour_soup', 'Acılı Ekşili Çorba', 'Hot and Sour Soup', 'chinese', '["energetic","stressed"]', '[]', 1, 0, 0, 'Bol baharatlı acı ekşi çorba.', 'Traditional spicy and sour Chinese soup.'),
('maki_rolls', 'Maki Rulo', 'Maki Rolls', 'japanese', '["happy","relaxed"]', '[]', 1, 0, 1, 'Sebzeli veya balıklı rulo suşiler.', 'Sushi rolls wrapped in seaweed.'),
('sashimi_fresh', 'Sashimi', 'Sashimi', 'japanese', '["relaxed","happy"]', '[]', 0, 0, 1, 'Taze çiğ balık dilimleri.', 'Slices of very fresh raw fish.'),
('agedashi_tofu', 'Agedashi Tofu', 'Agedashi Tofu', 'japanese', '["relaxed","happy"]', '[]', 1, 1, 0, 'Kızartılmış dashi soslu tofu.', 'Deep-fried tofu in a savory dashi broth.'),
('matcha_ice_cream', 'Matcha Dondurma', 'Matcha Ice Cream', 'japanese', '["happy","relaxed"]', '[]', 1, 0, 1, 'Japon usulü yeşil çaylı dondurma.', 'Japanese style green tea flavored ice cream.'),
('mochi_dessert', 'Mochi', 'Mochi', 'japanese', '["happy","relaxed"]', '[]', 1, 1, 1, 'Pirinç hamurlu Japon tatlısı.', 'Sweet Japanese rice cake.'),
('curry_pan', 'Köri Soslu Ekmek', 'Curry Pan', 'japanese', '["happy","energetic"]', '[]', 1, 0, 0, 'İçi köri dolgulu kızarmış ekmek.', 'Fried bread filled with Japanese curry.'),
('taiwanese_fried_chicken', 'Tayvan Tavuğu', 'Taiwanese Fried Chicken', 'chinese', '["happy","energetic"]', '[]', 0, 0, 0, 'Baharatlı büyük tavuk pirzolası.', 'Spicy large fried chicken steak from Taiwan.'),
('bubble_tea', 'Boba Çayı', 'Bubble Tea', 'chinese', '["happy","energetic"]', '[]', 1, 0, 1, 'İncili sütlü çay veya meyveli çay.', 'Tea-based drink with chewy tapioca pearls.'),
('dan_tat', 'Yumurtalı Tart', 'Egg Tart', 'chinese', '["happy","relaxed"]', '[]', 1, 0, 0, 'Hong Kong usulü çıtır tatlı tart.', 'Hong Kong style custard tart.');
