-- Massive Enriched Food Data - Batch 1 (100 items)
INSERT INTO foods (id, name_tr, name_en, cuisine, moods, regions, is_vegetarian, is_vegan, is_gluten_free, description_tr, description_en) VALUES
('adana_durum', 'Adana Dürüm', 'Adana Wrap', 'turkish', '["happy","energetic"]', '["akdeniz"]', 0, 0, 0, 'Lavaş arası acılı Adana kebabı.', 'Spicy Adana kebab in a wrap.'),
('lahmacun_citir', 'Çıtır Lahmacun', 'Crispy Lahmacun', 'turkish', '["happy","energetic"]', '["guneydogu"]', 0, 0, 0, 'İnce ve çıtır Türk pizzası.', 'Thin and crispy Turkish pizza.'),
('beyti_sarman', 'Beyti Sarma', 'Beyti Sarma', 'turkish', '["happy","relaxed"]', '["marmara"]', 0, 0, 0, 'Yufkaya sarılı kebap, domates sos ve yoğurt.', 'Kebab wrapped in bread with tomato sauce and yogurt.'),
('ali_nazik', 'Ali Nazik', 'Ali Nazik', 'turkish', '["happy","relaxed"]', '["guneydogu"]', 0, 0, 1, 'Yoğurtlu patlıcan yatağında kuzu eti.', 'Lamb meat on a bed of eggplant with yogurt.'),
('hunkar_begendi', 'Hünkar Beğendi', 'Hunkar Begendi', 'turkish', '["happy","relaxed"]', '["marmara"]', 0, 0, 1, 'Beğendi yatağında kuzu eti.', 'Lamb stew served on a bed of creamy eggplant puree.'),
('kuzu_tandir', 'Kuzu Tandır', 'Lamb Tandir', 'turkish', '["happy","tired"]', '["icanadolu"]', 0, 0, 1, 'Yavaş pişmiş kuzu eti.', 'Slow-roasted lamb meat.'),
('icli_kofte_haslama', 'Haşlama İçli Köfte', 'Boiled Kibbeh', 'turkish', '["happy","relaxed"]', '["guneydogu"]', 0, 0, 0, 'Haşlanmış dondurulmuş içli köfte.', 'Boiled stuffed bulgur balls.'),
('perde_pilavi', 'Perde Pilavı', 'Perde Pilavi', 'turkish', '["happy","relaxed"]', '["guneydogu"]', 0, 0, 0, 'Hamur kaplı bademli tavuklu pilav.', 'Rice with chicken and almonds wrapped in a thin dough.'),
('kuyu_kebab', 'Kuyu Kebabı', 'Pit Kebab', 'turkish', '["happy","tired"]', '["karadeniz"]', 0, 0, 1, 'Kuyuda pişmiş kuzu eti.', 'Lamb cooked in a special well/pit.'),
('ca_kebap', 'Oltu Cağ Kebabı', 'Oltu Cag Kebab', 'turkish', '["happy","energetic"]', '["doguanadolu"]', 0, 0, 1, 'Yatık döner kebabı.', 'Horizontal rotisserie kebab.'),
('tas_kebabi', 'Tas Kebabı', 'Tas Kebab', 'turkish', '["happy","tired"]', '["icanadolu"]', 0, 0, 1, 'Sebzeli kuzu eti yemeği.', 'Traditional lamb stew with vegetables.'),
('orman_kebabi', 'Orman Kebabı', 'Forest Kebab', 'turkish', '["relaxed","tired"]', '["marmara"]', 0, 0, 1, 'Bol sebzeli et yemeği.', 'Meat stew with plenty of vegetables.'),
('islim_kebabi', 'İslim Kebabı', 'Eggplant Manchet Kebab', 'turkish', '["happy","relaxed"]', '["marmara"]', 0, 0, 1, 'Patlıcan dilimlerine sarılı köfte.', 'Kebab wrapped in thin eggplant slices.'),
('kagit_kebabi', 'Kağıt Kebabı', 'Paper Kebab', 'turkish', '["happy","relaxed"]', '["akdeniz"]', 0, 0, 1, 'Kağıtta pişmiş sebzeli et.', 'Meat and vegetables cooked in parchment paper.'),
('belen_tava', 'Belen Tava', 'Belen Tava', 'turkish', '["happy","energetic"]', '["akdeniz"]', 0, 0, 1, 'Hatay usulü fırında et.', 'Hatay style baked meat dish.'),
('testi_kebabi', 'Testi Kebabı', 'Pottery Kebab', 'turkish', '["happy","relaxed"]', '["icanadolu"]', 0, 0, 1, 'Testi içinde pişen et.', 'Meat cooked in a sealed clay pot.'),
('abugannus', 'Abugannuş', 'Abugannush', 'turkish', '["relaxed","energetic"]', '["guneydogu"]', 1, 1, 1, 'Patlıcan ve biberli meze.', 'Roasted eggplant and pepper salad.'),
('muhammara', 'Muhammara', 'Muhammara', 'turkish', '["energetic","happy"]', '["akdeniz"]', 1, 1, 0, 'Cevizli ve biberli acı meze.', 'Spicy walnut and red pepper dip.'),
('babagannus', 'Babagannuş', 'Babaganoush', 'turkish', '["relaxed","happy"]', '["akdeniz"]', 1, 1, 1, 'Tahinli patlıcan ezmesi.', 'Smoked eggplant dip with tahini.'),
('haydari', 'Haydari', 'Haydari', 'turkish', '["relaxed","happy"]', '["marmara"]', 1, 0, 1, 'Süzme yoğurtlu meze.', 'Thick yogurt dip with herbs and garlic.'),
('atom', 'Atom', 'Atom', 'turkish', '["energetic","happy"]', '["ege"]', 1, 0, 1, 'Acı biberli yoğurtlu meze.', 'Spicy chili pepper yogurt dip.'),
('deniz_borulcesi', 'Deniz Börülcesi', 'Sea Beans', 'turkish', '["relaxed","energetic"]', '["ege"]', 1, 1, 1, 'Zeytinyağlı deniz börülcesi.', 'Samphire salad with olive oil and garlic.'),
('kabak_cicegi_dolmasi', 'Kabak Çiçeği Dolması', 'Stuffed Squash Blossoms', 'turkish', '["happy","relaxed"]', '["ege"]', 1, 1, 1, 'Zeytinyağlı kabak çiçeği dolması.', 'Squash blossoms stuffed with rice.'),
('fava', 'Fava', 'Fava', 'turkish', '["relaxed","happy"]', '["ege"]', 1, 1, 1, 'Zeytinyağlı bakla ezmesi.', 'Broad bean puree with dill and olive oil.'),
('karides_guvec', 'Karides Güveç', 'Shrimp Casserole', 'turkish', '["happy","relaxed"]', '["ege"]', 0, 0, 1, 'Peynirli karides güveç.', 'Shrimp baked in a clay pot with cheese.'),
('ahtapot_salatasi', 'Ahtapot Salatası', 'Octopus Salad', 'turkish', '["relaxed","energetic"]', '["ege"]', 0, 0, 1, 'Zeytinyağlı ahtapot salatası.', 'Octopus salad with olive oil and lemon.'),
('kalamar_tava', 'Kalamar Tava', 'Fried Calamari', 'turkish', '["happy","energetic"]', '["ege"]', 0, 0, 0, 'Tarator soslu kalamar tava.', 'Fried calamari rings with tarator sauce.'),
('midye_dolma', 'Midye Dolma', 'Stuffed Mussels', 'turkish', '["happy","energetic"]', '["marmara"]', 0, 0, 1, 'Baharatlı pirinç dolgulu midye.', 'Mussels stuffed with herbed rice.'),
('midye_tava', 'Midye Tava', 'Fried Mussels', 'turkish', '["happy","energetic"]', '["marmara"]', 0, 0, 0, 'Çıtır midye tava.', 'Crispy fried mussels on skewers.'),
('lakerda', 'Lakerda', 'Lakerda', 'turkish', '["relaxed","happy"]', '["marmara"]', 0, 0, 1, 'Tuzlanmış palamut eti.', 'Salt-cured bonito fish.'),
('pacanga_boregi', 'Paçanga Böreği', 'Pacanga Boregi', 'turkish', '["happy","energetic"]', '["marmara"]', 0, 0, 0, 'Pastırmalı ve kaşarlı börek.', 'Fried pastry with pastirma and cheese.'),
('su_boregi', 'Su Böreği', 'Water Borek', 'turkish', '["happy","tired"]', '["icanadolu"]', 1, 0, 0, 'Peynirli geleneksel su böreği.', 'Traditional multi-layered pastry boiled then baked.'),
('kol_boregi', 'Kol Böreği', 'Kol Boregi', 'turkish', '["happy","tired"]', '["marmara"]', 1, 0, 0, 'Kıymalı veya peynirli kol böreği.', 'Spiral shaped flaky pastry.'),
('sigara_boregi', 'Sigara Böreği', 'Cigarette Borek', 'turkish', '["happy","energetic"]', '["marmara"]', 1, 0, 0, 'Peynirli çıtır börek.', 'Crispy fried dough rolls with cheese.'),
('gul_boregi', 'Gül Böreği', 'Rose Borek', 'turkish', '["happy","relaxed"]', '["icanadolu"]', 1, 0, 0, 'Ispanaklı gül böreği.', 'Rose-shaped flaky pastry with spinach.'),
('kiymali_pide', 'Kıymalı Pide', 'Pide with Minced Meat', 'turkish', '["happy","energetic"]', '["karadeniz"]', 0, 0, 0, 'Kıymalı geleneksel Türk pidesi.', 'Turkish flatbread with minced meat.'),
('kusbasili_pide', 'Kuşbaşılı Pide', 'Pide with Diced Meat', 'turkish', '["happy","energetic"]', '["karadeniz"]', 0, 0, 0, 'Kuşbaşı etli pide.', 'Turkish flatbread with pieces of meat.'),
('kasarli_pide', 'Kaşarlı Pide', 'Pide with Cheese', 'turkish', '["happy","relaxed"]', '["karadeniz"]', 1, 0, 0, 'Bol kaşarlı pide.', 'Turkish flatbread with melted cheese.'),
('karisik_pide', 'Karışık Pide', 'Mixed Pide', 'turkish', '["happy","energetic"]', '["karadeniz"]', 0, 0, 0, 'Kıymalı, kuşbaşılı ve kaşarlı pide.', 'Turkish flatbread with mixed toppings.'),
('sac_tava', 'Sac Tava', 'Sac Tava', 'turkish', '["happy","energetic"]', '["guneydogu"]', 0, 0, 1, 'Sacda pişmiş baharatlı et.', 'Spicy meat stir-fried on a traditional iron plate.'),
('coban_kavurma', 'Çoban Kavurma', 'Shepherd''s Stir-fry', 'turkish', '["happy","tired"]', '["icanadolu"]', 0, 0, 1, 'Arpacık soğanlı kuzu kavurma.', 'Lamb stir-fry with shallots and peppers.'),
('kuzu_kapama', 'Kuzu Kapama', 'Lamb Kapama', 'turkish', '["relaxed","tired"]', '["marmara"]', 0, 0, 1, 'Taze soğanlı kuzu eti.', 'Lamb stew with spring onions and lettuce.'),
('elbasan_tava', 'Elbasan Tava', 'Elbasan Tava', 'turkish', '["happy","tired"]', '["marmara"]', 0, 0, 0, 'Yoğurt soslu fırınlanmış kuzu.', 'Lamb baked in a rich yogurt sauce.'),
('kadinbudu_kofte', 'Kadınbudu Köfte', 'Kadinbudu Kofta', 'turkish', '["happy","relaxed"]', '["marmara"]', 0, 0, 0, 'Pirinçli ve yumurtalı köfte.', 'Fried meatballs with rice and egg coating.'),
('ispanakli_kofte', 'Ispanaklı Köfte', 'Spinach Kofta', 'turkish', '["relaxed","happy"]', '["icanadolu"]', 1, 0, 0, 'Ispanaklı ve peynirli içli köfte.', 'Meatballs or bulgur balls stuffed with spinach.'),
('mercimek_koftesi', 'Mercimek Köftesi', 'Lentil Balls', 'turkish', '["happy","relaxed"]', '["icanadolu"]', 1, 1, 1, 'Kırmızı mercimekli soğuk köfte.', 'Cold vegetarian balls made of red lentils and bulgur.'),
('fellah_koftesi', 'Fellah Köftesi', 'Fellah Kofta', 'turkish', '["energetic","happy"]', '["akdeniz"]', 1, 1, 0, 'Sarımsaklı ve domates soslu bulgur köftesi.', 'Bulgur balls with garlic and tomato sauce.'),
('analikizli', 'Analı Kızlı', 'Analikizli', 'turkish', '["happy","relaxed"]', '["guneydogu"]', 0, 0, 0, 'Büyük ve küçük içli köftelerin çorbası.', 'Soup with large and small stuffed bulgur balls.'),
('Yuvalama', 'Yuvalama', 'Yuvalama', 'turkish', '["happy","relaxed"]', '["guneydogu"]', 0, 0, 1, 'Gaziantep usulü yoğurtlu bayram çorbası.', 'Gaziantep style yogurt soup with meat and rice balls.'),
('beyran', 'Beyran Çorbası', 'Beyran Soup', 'turkish', '["energetic","happy"]', '["guneydogu"]', 0, 0, 1, 'Acılı ve sarımsaklı kuzu eti çorbası.', 'Spicy lamb and rice soup with garlic.'),
('ezogelin', 'Ezogelin Çorbası', 'Ezogelin Soup', 'turkish', '["sad","tired"]', '["icanadolu"]', 1, 1, 0, 'Baharatlı kırmızı mercimek çorbası.', 'Spicy red lentil and bulgur soup.'),
('yayla_corbasi', 'Yayla Çorbası', 'Yayla Soup', 'turkish', '["relaxed","sad"]', '["icanadolu"]', 1, 0, 0, 'Yoğurtlu ve naneli pirinç çorbası.', 'Yogurt soup with rice and mint.'),
('tarhana_corbasi', 'Tarhana Çorbası', 'Tarhana Soup', 'turkish', '["sad","tired"]', '["icanadolu"]', 1, 0, 0, 'Geleneksel Anadolu tarhana çorbası.', 'Traditional fermented grain and yogurt soup.'),
('dugun_corbasi', 'Düğün Çorbası', 'Wedding Soup', 'turkish', '["happy","relaxed"]', '["icanadolu"]', 0, 0, 0, 'Yoğurtlu kuzu eti çorbası.', 'Rich yogurt soup with shredded lamb meat.'),
('domates_corbasi', 'Domates Çorbası', 'Tomato Soup', 'turkish', '["relaxed","happy"]', '["marmara"]', 1, 0, 0, 'Kaşarlı taze domates çorbası.', 'Fresh tomato soup with grated cheese.'),
('kelle_paca', 'Kelle Paça', 'Sheep Head and Trotter Soup', 'turkish', '["energetic","tired"]', '["marmara"]', 0, 0, 1, 'Sarımsaklı ve sirkeli sakatat çorbası.', 'Traditonal soup made from sheep parts with garlic.'),
('iskembe_corbasi', 'İşkembe Çorbası', 'Tripe Soup', 'turkish', '["energetic","tired"]', '["marmara"]', 0, 0, 1, 'Sirkeli ve sarımsaklı işkembe çorbası.', 'Tripe soup served with garlic and vinegar.'),
('zeytinyagli_enginar', 'Zeytinyağlı Enginar', 'Artichoke in Olive Oil', 'turkish', '["relaxed","happy"]', '["ege"]', 1, 1, 1, 'Bezelye ve havuçlu enginar.', 'Artichokes with peas and carrots in olive oil.'),
('zeytinyagli_taze_fasulye', 'Zeytinyağlı Taze Fasulye', 'Green Beans in Olive Oil', 'turkish', '["relaxed","happy"]', '["ege"]', 1, 1, 1, 'Domatesli taze fasulye.', 'Green beans cooked with tomatoes in olive oil.'),
('zeytinyagli_bamya', 'Zeytinyağlı Bamya', 'Okra in Olive Oil', 'turkish', '["relaxed","happy"]', '["ege"]', 1, 1, 1, 'Limonlu ve domatesli bamya.', 'Okra cooked with lemon and tomatoes in olive oil.'),
('zeytinyagli_kereviz', 'Zeytinyağlı Kereviz', 'Celery Root in Olive Oil', 'turkish', '["relaxed","happy"]', '["marmara"]', 1, 1, 1, 'Portakallı kereviz.', 'Celery root cooked with orange juice and olive oil.'),
('zeytinyagli_pirasa', 'Zeytinyağlı Pırasa', 'Leeks in Olive Oil', 'turkish', '["relaxed","happy"]', '["marmara"]', 1, 1, 1, 'Havuçlu ve pirinçli pırasa.', 'Leeks cooked with carrots and rice in olive oil.'),
('imambayildi', 'İmambayıldı', 'Imambayildi', 'turkish', '["happy","relaxed"]', '["marmara"]', 1, 1, 1, 'Soğanlı ve sarımsaklı patlıcan dolması.', 'Eggplant stuffed with onion, garlic and tomatoes.'),
('karniyarik', 'Karnıyarık', 'Karniyarik', 'turkish', '["happy","tired"]', '["icanadolu"]', 0, 0, 1, 'Kıymalı patlıcan dolması.', 'Eggplant stuffed with minced meat and tomatoes.'),
('yaprak_sarma', 'Zeytinyağlı Yaprak Sarma', 'Stuffed Grape Leaves', 'turkish', '["happy","relaxed"]', '["ege"]', 1, 1, 1, 'Pirinçli asma yaprağı sarması.', 'Grape leaves stuffed with herbed rice.'),
('lahana_sarmasi', 'Lahana Sarması', 'Stuffed Cabbage Rolls', 'turkish', '["happy","tired"]', '["karadeniz"]', 0, 0, 1, 'Kıymalı lahana sarması.', 'Cabbage leaves stuffed with minced meat and rice.'),
('biber_dolmasi', 'Biber Dolması', 'Stuffed Peppers', 'turkish', '["happy","relaxed"]', '["icanadolu"]', 0, 0, 1, 'Kıymalı veya zeytinyağlı biber dolması.', 'Bell peppers stuffed with rice and spices.'),
('kabak_dolmasi', 'Kabak Dolması', 'Stuffed Zucchini', 'turkish', '["happy","relaxed"]', '["icanadolu"]', 0, 0, 1, 'Kıymalı kabak dolması.', 'Zucchini stuffed with minced meat and rice.'),
('etli_kuru_fasulye', 'Etli Kuru Fasulye', 'White Bean Stew with Meat', 'turkish', '["happy","tired"]', '["icanadolu"]', 0, 0, 1, 'Sucuklu veya etli kuru fasulye.', 'Traditional white bean stew with meat or sucuk.'),
('etli_nohut', 'Etli Nohut', 'Chickpea Stew with Meat', 'turkish', '["happy","tired"]', '["icanadolu"]', 0, 0, 1, 'Kuzu etli nohut yemeği.', 'Chickpea stew with lamb or beef.'),
('kiymali_ispanak', 'Kıymalı Ispanak', 'Spinach with Minced Meat', 'turkish', '["relaxed","tired"]', '["marmara"]', 0, 0, 1, 'Yoğurtlu kıymalı ıspanak.', 'Spinach cooked with minced meat, served with yogurt.'),
('taze_bakla', 'Taze Bakla', 'Fresh Fava Beans', 'turkish', '["relaxed","happy"]', '["ege"]', 1, 1, 1, 'Dereotlu taze bakla.', 'Fresh fava beans with dill and yogurt or olive oil.'),
('semizotu_yemegi', 'Semizotu Yemeği', 'Purslane Stew', 'turkish', '["relaxed","energetic"]', '["marmara"]', 1, 0, 1, 'Pirinçli semizotu yemeği.', 'Purslane cooked with rice and tomatoes, served with yogurt.'),
('ekşili_köfte', 'Ekşili Köfte', 'Sour Meatballs', 'turkish', '["happy","relaxed"]', '["marmara"]', 0, 0, 0, 'Terbiyeli sulu köfte.', 'Meatballs in a lemon and egg sauce stew.'),
('izmir_kofte', 'İzmir Köfte', 'Izmir Kofta', 'turkish', '["happy","tired"]', '["ege"]', 0, 0, 1, 'Patatesli ve biberli fırın köfte.', 'Baked meatballs with potatoes and green peppers.'),
('kadin_budu', 'Kadınbudu Köfte', 'Kadinbudu Kofta', 'turkish', '["happy","relaxed"]', '["marmara"]', 0, 0, 0, 'Pirinçli ve yumurtalı köfte.', 'Fried meatballs with rice and egg coating.'),
('sultan_kebabi', 'Sultan Kebabı', 'Sultan Kebab', 'turkish', '["happy","relaxed"]', '["marmara"]', 0, 0, 0, 'Yufka içinde beşamel soslu et.', 'Meat and vegetables in dough with bechamel sauce.'),
('hasan_pasa_koftesi', 'Hasan Paşa Köftesi', 'Hasan Pasha Kofta', 'turkish', '["happy","relaxed"]', '["marmara"]', 0, 0, 1, 'Patates püreli çanak köfte.', 'Meatball cups topped with mashed potatoes.'),
('dalyan_kofte', 'Dalyan Köfte', 'Dalyan Kofta', 'turkish', '["happy","relaxed"]', '["marmara"]', 0, 0, 0, 'Rulo köfte içinde yumurta ve sebze.', 'Meatloaf with hard-boiled eggs and vegetables inside.'),
('terbiyeli_kofte', 'Terbiyeli Köfte', 'Seasoned Meatballs', 'turkish', '["relaxed","sad"]', '["marmara"]', 0, 0, 0, 'Yoğurt soslu sulu köfte.', 'Meatballs in a yogurt and egg sauce.'),
('sirkeli_kofte', 'Sirkeli Köfte', 'Vinegared Meatballs', 'turkish', '["energetic","happy"]', '["icanadolu"]', 0, 0, 1, 'Sarımsak ve sirkeli köfte.', 'Meatballs cooked with garlic and vinegar.'),
('tekirdag_koftesi', 'Tekirdağ Köftesi', 'Tekirdag Kofta', 'turkish', '["happy","energetic"]', '["marmara"]', 0, 0, 1, 'Tekirdağ usulü ızgara köfte.', 'Grilled meatballs specific to Tekirdag.'),
('akcaabat_koftesi', 'Akçaabat Köftesi', 'Akcaabat Kofta', 'turkish', '["happy","energetic"]', '["karadeniz"]', 0, 0, 1, 'Sarımsaklı Akçaabat köftesi.', 'Garlic meatballs from Akcaabat, Trabzon.'),
('islama_kofte', 'Islama Köfte', 'Islama Kofta', 'turkish', '["happy","tired"]', '["marmara"]', 0, 0, 0, 'Soslu ekmekli Sakarya köftesi.', 'Grilled meatballs served on bone broth soaked bread.'),
('tire_sis_kofte', 'Tire Şiş Köfte', 'Tire Shish Kofta', 'turkish', '["happy","relaxed"]', '["ege"]', 0, 0, 1, 'Domates soslu Tire kebabı.', 'Grilled meatballs on skewers with tomato sauce.'),
('pideli_kofte', 'Pideli Köfte', 'Kofta with Pide', 'turkish', '["happy","relaxed"]', '["marmara"]', 0, 0, 0, 'Bursa usulü pideli köfte.', 'Grilled meatballs served on pieces of pide bread.'),
('sulu_kofte', 'Sulu Köfte', 'Meatball Stew', 'turkish', '["sad","tired"]', '["icanadolu"]', 0, 0, 0, 'Patatesli sulu köfte yemeği.', 'Stew with meatballs and potatoes.'),
('mercimekli_bulgur_pilavi', 'Mercimekli Bulgur Pilavı', 'Bulgur Rice with Lentils', 'turkish', '["relaxed","happy"]', '["guneydogu"]', 1, 1, 0, 'Yeşil mercimekli bulgur pilavı.', 'Bulgur pilaf with green lentils.'),
('sehriyeli_pirinc_pilavi', 'Şehriyeli Pirinç Pilavı', 'Rice Pilaf with Orzo', 'turkish', '["happy","relaxed"]', '["icanadolu"]', 1, 0, 0, 'Tereyağlı pirinç pilavı.', 'Butter rice pilaf with orzo.'),
('meyhane_pilavi', 'Meyhane Pilavı', 'Meyhane Pilaf', 'turkish', '["happy","energetic"]', '["guneydogu"]', 1, 1, 0, 'Sebzeli bulgur pilavı.', 'Bulgur pilaf with tomatoes, peppers and onions.'),
('perde_pilavi_siirt', 'Siirt Perde Pilavı', 'Siirt Perde Pilavi', 'turkish', '["happy","relaxed"]', '["guneydogu"]', 0, 0, 0, 'Keklik veya tavuklu perde pilavı.', 'Traditional festive rice dish with partridge or chicken.'),
('ozbek_pilavi', 'Özbek Pilavı', 'Uzbek Pilaf', 'turkish', '["happy","relaxed"]', '["marmara"]', 0, 0, 1, 'Etli ve havuçlu Özbek pilavı.', 'Uzbek style rice pilaf with meat and carrots.'),
('bugday_pilavi', 'Buğday Pilavı', 'Wheat Pilaf', 'turkish', '["relaxed","happy"]', '["icanadolu"]', 1, 1, 0, 'Yoğurtlu buğday pilavı.', 'Pilaf made from whole wheat grains.'),
('keskek', 'Keşkek', 'Keskek', 'turkish', '["happy","relaxed"]', '["ege"]', 0, 0, 0, 'Etli ve buğdaylı geleneksel yemek.', 'Ceremonial dish of meat and wheat porridge.'),
('menemen_sucuklu', 'Sucuklu Menemen', 'Menemen with Sucuk', 'turkish', '["happy","energetic"]', '["icanadolu"]', 0, 0, 1, 'Sucuklu ve yumurtalı menemen.', 'Turkish scrambled eggs with tomatoes and sucuk.'),
('pastirmali_yumurta', 'Pastırmalı Yumurta', 'Eggs with Pastirma', 'turkish', '["happy","relaxed"]', '["icanadolu"]', 0, 0, 1, 'Fırında pastırmalı yumurta.', 'Fried eggs with pastirma (cured beef).'),
('cilbir', 'Çılbır', 'Cilbir', 'turkish', '["relaxed","happy"]', '["icanadolu"]', 1, 0, 1, 'Yoğurtlu poşe yumurta.', 'Poached eggs with yogurt and chili butter.'),
('muhlama', 'Muhlama', 'Muhlama', 'turkish', '["happy","tired"]', '["karadeniz"]', 1, 0, 1, 'Mısır unu ve peynirli Karadeniz kahvaltısı.', 'Cheese and cornmeal fondue from Black Sea region.'),
('kaygana', 'Kaygana', 'Kaygana', 'turkish', '["happy","energetic"]', '["karadeniz"]', 1, 0, 0, 'Karadeniz usulü sebzeli krep.', 'Turkish style crepes with vegetables/herbs.');
