-- Migration data for foods table
INSERT INTO foods (id, name_tr, name_en, cuisine, moods, regions, is_vegetarian, is_vegan, is_gluten_free) VALUES
('pizza_veg', 'Sebzeli Pizza', 'Vegetable Pizza', 'italian', '["happy","energetic","relaxed"]', '[]', 1, 0, 0),
('pasta', 'Makarna', 'Pasta', 'italian', '["happy","sad","tired"]', '[]', 1, 0, 0),
('sushi_veg', 'Sebze Sushi', 'Vegetable Sushi', 'japanese', '["happy","relaxed"]', '[]', 1, 1, 1),
('burger', 'Hamburger', 'Burger', 'american', '["happy","energetic","stressed"]', '[]', 0, 0, 0),
('soup', 'Mercimek Çorbası', 'Lentil Soup', 'turkish', '["sad","tired","relaxed"]', '[]', 1, 1, 1),
('kebab_antep', 'Antep Kebabı', 'Antep Kebab', 'turkish', '["happy","relaxed","energetic"]', '["guneydogu"]', 0, 0, 1),
('kunefe', 'Künefe', 'Kunefe', 'turkish', '["happy","sad","relaxed"]', '["akdeniz","guneydogu"]', 1, 0, 0),
('chocolate', 'Çikolata', 'Chocolate', 'snack', '["sad","stressed","happy"]', '[]', 1, 0, 1),
('icecream', 'Dondurma', 'Ice Cream', 'world', '["sad","happy","relaxed"]', '[]', 1, 0, 1),
('salad', 'Yeşil Salata', 'Green Salad', 'world', '["energetic","relaxed"]', '[]', 1, 1, 1),
('smoothie', 'Smoothie', 'Smoothie', 'world', '["energetic","happy"]', '[]', 1, 1, 1),
('coffee', 'Kahve', 'Coffee', 'world', '["tired","stressed"]', '[]', 1, 1, 1),
('tea', 'Bitki Çayı', 'Herbal Tea', 'world', '["stressed","relaxed","tired"]', '[]', 1, 1, 1),
('nuts', 'Kuruyemiş', 'Nuts', 'turkish', '["stressed","tired","energetic"]', '[]', 1, 1, 1),
('falafel', 'Falafel', 'Falafel', 'middle_eastern', '["happy","energetic"]', '[]', 1, 1, 1),
('hummus', 'Humus', 'Hummus', 'middle_eastern', '["relaxed","energetic"]', '[]', 1, 1, 1),
('taco', 'Taco', 'Taco', 'mexican', '["happy","energetic"]', '[]', 0, 0, 1),
('ramen', 'Ramen', 'Ramen', 'japanese', '["happy","tired","sad"]', '[]', 0, 0, 0),
('butter_chicken', 'Butter Chicken', 'Butter Chicken', 'indian', '["happy","relaxed"]', '[]', 0, 0, 1),
('baklava_antep', 'Antep Baklavası', 'Antep Baklava', 'turkish', '["happy","sad","relaxed"]', '["guneydogu"]', 1, 0, 0),
('lahmacun_urfa', 'Urfa Lahmacunu', 'Urfa Lahmacun', 'turkish', '["happy","energetic","tired"]', '["guneydogu"]', 0, 0, 0),
('cig_kofte', 'Çiğ Köfte', 'Chee Kofta', 'turkish', '["energetic","happy"]', '["guneydogu"]', 1, 1, 0),
('katmer', 'Katmer', 'Katmer', 'turkish', '["happy","relaxed"]', '["guneydogu"]', 1, 0, 0),
('kuymak', 'Kuymak (Muhlama)', 'Kuymak', 'turkish', '["sad","tired","relaxed"]', '["karadeniz"]', 1, 0, 1),
('hamsi', 'Hamsi Tava', 'Fried Anchovies', 'turkish', '["happy","energetic"]', '["karadeniz"]', 0, 0, 1),
('pide_karadeniz', 'Karadeniz Pidesi', 'Black Sea Pide', 'turkish', '["happy","tired","relaxed"]', '["karadeniz"]', 1, 0, 0),
('laz_boregi', 'Laz Böreği', 'Laz Boregi', 'turkish', '["happy","sad","relaxed"]', '["karadeniz"]', 1, 0, 0),
('zeytinyagli', 'Zeytinyağlılar', 'Olive Oil Dishes', 'turkish', '["relaxed","energetic","happy"]', '["ege"]', 1, 1, 1),
('boyoz', 'Boyoz', 'Boyoz', 'turkish', '["happy","tired"]', '["ege"]', 1, 0, 0),
('kumru', 'Kumru', 'Kumru Sandwich', 'turkish', '["happy","energetic"]', '["ege"]', 0, 0, 0),
('lokma', 'İzmir Lokması', 'Izmir Loukoumades', 'turkish', '["happy","sad"]', '["ege"]', 1, 0, 0),
('adana_kebab', 'Adana Kebabı', 'Adana Kebab', 'turkish', '["happy","energetic","stressed"]', '["akdeniz"]', 0, 0, 1),
('salgam', 'Şalgam', 'Shalgam', 'turkish', '["energetic","happy"]', '["akdeniz"]', 1, 1, 1),
('tantuni', 'Tantuni', 'Tantuni', 'turkish', '["happy","energetic","tired"]', '["akdeniz"]', 0, 0, 0),
('manti_kayseri', 'Kayseri Mantısı', 'Kayseri Manti', 'turkish', '["sad","relaxed","happy"]', '["icanadolu"]', 1, 0, 0),
('etli_ekmek', 'Konya Etli Ekmek', 'Konya Etli Ekmek', 'turkish', '["happy","tired","energetic"]', '["icanadolu"]', 0, 0, 0),
('pastirma', 'Pastırma', 'Pastirma', 'turkish', '["happy","energetic"]', '["icanadolu"]', 0, 0, 1),
('ankara_tava', 'Ankara Tava', 'Ankara Tava', 'turkish', '["happy","tired","relaxed"]', '["icanadolu"]', 0, 0, 1),
('iskender', 'İskender Kebab', 'Iskender Kebab', 'turkish', '["happy","relaxed","tired"]', '["marmara"]', 0, 0, 0),
('inegol_kofte', 'İnegöl Köfte', 'Inegol Kofta', 'turkish', '["happy","energetic"]', '["marmara"]', 0, 0, 1),
('kestane_sekeri', 'Kestane Şekeri', 'Candied Chestnuts', 'turkish', '["happy","sad","relaxed"]', '["marmara"]', 1, 1, 1),
('balik_ekmek', 'Balık Ekmek', 'Fish Bread', 'turkish', '["happy","relaxed"]', '["marmara"]', 0, 0, 0),
('kokorec', 'Kokoreç', 'Kokorec', 'turkish', '["happy","energetic","tired"]', '["marmara"]', 0, 0, 1),
('cag_kebabi', 'Cağ Kebabı', 'Cag Kebab', 'turkish', '["happy","energetic"]', '["doguanadolu"]', 0, 0, 1),
('kars_gravyer', 'Kars Gravyeri ile Kahvaltı', 'Kars Gruere Breakfast', 'turkish', '["happy","relaxed"]', '["doguanadolu"]', 1, 0, 1),
('kadayif_dolmasi', 'Kadayıf Dolması', 'Kadayif Dolma', 'turkish', '["happy","sad","relaxed"]', '["doguanadolu"]', 1, 0, 0),
('kuru_kayisi', 'Malatya Kayısısı', 'Malatya Apricots', 'turkish', '["energetic","happy","tired"]', '["doguanadolu"]', 1, 1, 1);
